version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - /frontend:/app
    stdin_open: true
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
    - /app/node_modules
    - /frontend:/app
    command: ["npm", "run", "test"]

# web container created above is equivalent to:
# $ docker build -f Dockerfile.dev .
# $ docker run -itp 3000:3000 -v /app/node_modules -v //fronend://app

# tests
# we can also use same web container, and run tests with $ docker exec in a new cmd prompt/shell